const ErrorCodes = {
    "001": "Tank cannot move out of bounds.",
    "002": "Invalid cardinal direction.",
    "003": "You do not have enough action tokens.",
    "004": "The game has already started. No more players can join.",
    "005": "You cannot cast a vote if you are not part of the Jury.",
    "006": "You cannot cast a vote for a deceased player.",
    "007": "Player does not exist.",
    "008": "You are not allowed to move to another player's space.",
    "009": "Invalid coordinates.",
    "010": "You do not have enough range.",
    "011": "You cannot shoot at nothing.",
    "012": "You have already joined the game.",
    "013": "Game has already started.",
    "014": "No players to display.",
    "015": "Game has already started. Dummy data cannot be added.",
    "016": "A player with that nickname has already joined.",
    "017": "The game has not started yet.",
    "018": "Game settings cannot be changed in the middle of the game.",
    "019": "Setting does not exist. Use `!get-settings` to see a list of available settings.",
    "020": "Setting must be set to a whole number.",
    "021": "Setting must be a boolean (either `true` or `false`)",
    "022": "Setting value is not valid",
    "023": "You haven't joined the game yet! Use `!join` to join the game.",
    "024": "Tokens cannot be given out until the game has started.",
    "025": "You are dead. You cannot use that command.",
    "026": "",
    "027": "",
    "028": "",
    "029": "",
    "030": ""
}

export default ErrorCodes